/**
 * @file parts.hpp
 * @author Kiju
 *
 * @brief Collection of physics parts for the physics engine.
 * @note Coordinate convention: right-handed, Y-up, consistent with GLM defaults.
 *
 * @warning Majority of math-heavy code here was generated by an LLM.
 */

#pragma once

#include "glm/geometric.hpp"

#include "fr/core/array.hpp"
#include "fr/core/macros.hpp"
#include "fr/core/math.hpp"
#include "fr/core/meta.hpp"
#include "fr/core/shape.hpp"
#include "fr/core/typedefs.hpp"
#include "fr/data/thing.hpp"

namespace fr {

// =========================================================================== Mass

/**
 * @brief Rigid body mass properties.
 *
 * @details
 * Stores *inverse* quantities to avoid per-frame division in the physics integrator.
 * Set `inv_mass = 0` (and `inv_inertia = Mat3(0)`) for a static / kinematic body.
 * The inertia tensor is stored in **local body space**; the physics system rotates it to world
 * space each step as needed: I_world = R * inv_inertia * R^T.
 */
struct MassPart {
    Mat3 inv_inertia{1.0f};
    F32 inv_mass{1.0f};
    F32 restitution{0.5f};

    /**
     * @brief Center of mass in **local body space** (metres from the body origin).
     *
     * @details
     * Used by the constraint solver to find the moment arm from the COM to the
     * contact point, which determines the torque applied by each impulse.
     * For geometrically symmetric bodies whose mesh origin coincides with the
     * COM this is `{0, 0, 0}`.
     */
    Vec3 com{0.0f, 0.0f, 0.0f};

    FR_SHAPE({
        FR_PROP(inv_inertia);
        FR_PROP(inv_mass);
        FR_PROP(restitution);
        FR_PROP(com);
    })

    /// @brief Returns the actual mass value (0 if this is a static / infinite-mass body).
    F32 mass() const noexcept {
        return inv_mass > 0.0f ? 1.0f / inv_mass : 0.0f;
    }

    /// @brief Creates a mass with a scalar `m` and identity (isotropic) inertia tensor.
    static MassPart from_mass(F32 m, F32 restitution = 0.5f) noexcept {
        FR_ASSERT(m > 0.0f, "mass must be positive");
        return {Mat3(1.0f / m), 1.0f / m, restitution};
    }

    /// @brief Creates an immovable body (inv_mass = 0, zero inertia).
    static MassPart infinite() noexcept {
        return {Mat3(0.0f), 0.0f, 0.0f};
    }

    /// @brief Solid sphere: I = (2/5) * m * r^2 on each diagonal axis.
    static MassPart from_sphere(F32 m, F32 radius, F32 restitution = 0.5f) noexcept {
        FR_ASSERT(m > 0.0f && radius > 0.0f, "mass and radius must be positive");

        const F32 i_inv = 5.0f / (2.0f * m * radius * radius);
        return {Mat3(i_inv), 1.0f / m, restitution};
    }

    /**
     * @brief Solid box: Ix = (1/3)*m*(hy^2+hz^2), Iy = (1/3)*m*(hx^2+hz^2), Iz =
     * (1/3)*m*(hx^2+hy^2).
     *
     * @param half_extents Half-dimensions along each axis (hx, hy, hz).
     */
    static MassPart from_box(F32 m, Vec3 half_extents, F32 restitution = 0.5f) noexcept {
        FR_ASSERT(m > 0.0f, "mass must be positive");

        const F32 k = m / 3.0f;
        const F32 hx2 = half_extents.x * half_extents.x;
        const F32 hy2 = half_extents.y * half_extents.y;
        const F32 hz2 = half_extents.z * half_extents.z;

        Mat3 inv_i(0.0f);
        inv_i[0][0] = 1.0f / (k * (hy2 + hz2));
        inv_i[1][1] = 1.0f / (k * (hx2 + hz2));
        inv_i[2][2] = 1.0f / (k * (hx2 + hy2));

        return {inv_i, 1.0f / m, restitution};
    }
};

// ========================================================= Broad-Phase Volumes

/**
 * @brief Axis-Aligned Bounding Box in world space.
 * @note Defined by its minimum and maximum corner points. Used for broad-phase collision detection.
 */
struct AABB {
    Vec3 min{};
    Vec3 max{};

    FR_SHAPE({
        FR_PROP(min);
        FR_PROP(max);
    })

    /// @brief Returns the center of the box.
    Vec3 center() const noexcept {
        return (min + max) * 0.5f;
    }

    /// @brief Returns the half-extents (half the size along each axis).
    Vec3 half_extents() const noexcept {
        return (max - min) * 0.5f;
    }

    /// @brief Returns true if `point` is inside or on the boundary.
    bool contains(const Vec3 &point) const noexcept {
        return point.x >= min.x && point.x <= max.x && point.y >= min.y && point.y <= max.y &&
               point.z >= min.z && point.z <= max.z;
    }

    /// @brief Returns true if this box overlaps `other` (touching counts as overlap).
    bool overlaps(const AABB &other) const noexcept {
        return min.x <= other.max.x && max.x >= other.min.x && min.y <= other.max.y &&
               max.y >= other.min.y && min.z <= other.max.z && max.z >= other.min.z;
    }

    /// @brief Creates an AABB from a center point and half-extents.
    static AABB from_center(Vec3 center, Vec3 half_extents) noexcept {
        return {center - half_extents, center + half_extents};
    }
};

// ==================================================================== Collider

/**
 * @brief An AABB collision primitive attached to a thing.
 *
 * @details
 * `offset` is in local space and is added when computing the world-space bounds so the
 * primitive can be positioned independently of the thing's origin.
 */
struct ColliderPart {
    AABB aabb{};
    Vec3 offset{};

    FR_SHAPE({
        FR_PROP(aabb);
        FR_PROP(offset);
    })

    /// @brief Creates a collider from a local-space AABB with an optional offset.
    static ColliderPart make(AABB box, Vec3 offset = {}) noexcept {
        return {box, offset};
    }
};

/// @brief Represents a collision manifold between two things.
struct CollisionManifold {
    Thing a;
    Thing b;

    Vec3 normal{};
    Vec3 point{};
    F32 depth{0};

    FR_SHAPE({
        FR_PROP(a);
        FR_PROP(b);
        FR_PROP(normal);
        FR_PROP(point);
        FR_PROP(depth);
    })
};

// ============================================================ Collision Events

/**
 * @brief Records the things that collided with a given thing this frame.
 *
 * @details
 * `count` is the number of valid entries; slots beyond `count` are stale/nil.
 * Capped at MAX_COLLISIONS - excess contacts are silently dropped (broad phase
 * should keep this small in practice).
 */
struct CollisionEventsPart {
    static constexpr USize MAX_COLLISIONS = 16;

    USize count{0};
    Array<Thing, MAX_COLLISIONS> contacts{
        Array<Thing, MAX_COLLISIONS>::from_repeated(Thing::nil())};

    FR_SHAPE({
        FR_PROP(count);
        FR_PROP(contacts);
    })

    /// @brief Returns true if `p` thing appears in the current contact list.
    bool has(Thing thing) const noexcept {
        for (USize i = 0; i < count; ++i) {
            if (contacts[i] == thing) {
                return true;
            }
        }

        return false;
    }

    /**
     * @brief Inserts `thing` into the contact list if there is room.
     * @return True if the contact was inserted, false if the list is full.
     */
    bool insert(Thing thing) {
        if (count < MAX_COLLISIONS) {
            contacts[count++] = thing;
            return true;
        }

        return false;
    }
};

// ============================================================ Physics Material

/**
 * @brief Surface response parameters for collision resolution.
 *
 * @details
 * When two bodies collide, the solver typically combines their materials  to compute a single
 * friction and restitution value for the contact.
 */
struct PhysicsMaterialPart {
    F32 friction{0.5f};
    F32 restitution{0.5f};

    FR_SHAPE({
        FR_PROP(friction);
        FR_PROP(restitution);
    })
};

// ================================================================== Rigid Body

/**
 * @brief Dynamics state for a rigid body..
 *
 * @details
 * Pair this part with a `MassPart` (which carries `inv_inertia` and the `com` offset)
 * to get rotational dynamics.  Without `MassPart` the body still moves linearly but
 * never accumulates angular velocity.
 *
 * Bodies with `inv_mass == 0` are immovable static bodies - all force, impulse, and
 * integration steps are no-ops for them.
 */
struct RigidBodyPart {
    /// @brief Linear velocity in world space (m/s).
    Vec3 velocity{0.0f, 0.0f, 0.0f};

    /// @brief Angular velocity in world space (rad/s); axis direction = rotation axis, magnitude =
    /// speed.
    Vec3 angular_velocity{0.0f, 0.0f, 0.0f};

    /// @brief Accumulated external force for this frame (N). Cleared after integration.
    Vec3 force{0.0f, 0.0f, 0.0f};

    /// @brief Accumulated external torque for this frame (N·m). Cleared after integration.
    Vec3 torque{0.0f, 0.0f, 0.0f};

    /// @brief Inverse mass (kg⁻¹). Set to 0 for a static / infinite-mass body.
    F32 inv_mass{1.0f};

    /**
     * @brief Coefficient of restitution (bounciness), in [0, 1].
     *
     * 0 = perfectly inelastic, 1 = perfectly elastic.
     * The solver uses the geometric mean of the two colliding bodies.
     */
    F32 restitution{0.3f};

    /**
     * @brief Coefficient of friction (Coulomb model), in [0, 1].
     *
     * The solver uses the geometric mean of the two colliding bodies.
     * Ignored for contacts involving a sphere collider.
     */
    F32 friction{0.5f};

    FR_SHAPE({
        FR_PROP(velocity);
        FR_PROP(angular_velocity);
        FR_PROP(force);
        FR_PROP(torque);
        FR_PROP(inv_mass);
        FR_PROP(restitution);
        FR_PROP(friction);
    })

    /// @brief Creates a dynamic body with the given mass (kg) and optional surface properties.
    static RigidBodyPart make_dynamic(F32 mass, F32 restitution = 0.3f,
                                      F32 friction = 0.5f) noexcept {
        FR_ASSERT(mass > 0.0f, "mass must be positive");

        RigidBodyPart rb;
        rb.inv_mass = 1.0f / mass;
        rb.restitution = restitution;
        rb.friction = friction;

        return rb;
    }

    /// @brief Creates an immovable static body (inv_mass = 0).
    static RigidBodyPart make_static(F32 restitution = 0.3f, F32 friction = 0.5f) noexcept {
        RigidBodyPart rb;
        rb.inv_mass = 0.0f;
        rb.restitution = restitution;
        rb.friction = friction;

        return rb;
    }

    /// @brief Returns the actual mass in kg (0 if this is a static body).
    F32 mass() const noexcept {
        return inv_mass > 0.0f ? 1.0f / inv_mass : 0.0f;
    }
};

// ============================================================= Collision Tests

/// @brief Returns true if two AABBs overlap (touching counts).
inline bool check_collision(const AABB &a, const AABB &b) noexcept {
    return a.overlaps(b);
}

/// @brief Returns true if two ColliderParts overlap.
inline bool check_collision(const ColliderPart &a, const ColliderPart &b) noexcept {
    return check_collision(a.aabb, b.aabb);
}

// ======================================================== Manifold Computation

/**
 * @brief Result of a narrow-phase collision test.
 *
 * @details If `hit` is false, the `manifold` field is uninitialised and must not be read.
 * The `Thing` fields inside `manifold` are left as `Thing::nil()` - the caller (narrowphase
 * system) is responsible for filling them in before storing the manifold.
 */
struct CollisionManifoldResult {
    bool hit{false};
    CollisionManifold manifold{};
};

/**
 * @brief Computes the contact manifold for two overlapping AABBs using SAT.
 *
 * @details Picks the axis with minimum penetration depth as the separation axis.
 * The manifold normal points from `b` toward `a` (resolves `a` when applied positively).
 * `point` is the centre of the overlap interval along the contact axis.
 *
 * @return `{false, {}}` when the AABBs do not overlap.
 */
inline CollisionManifoldResult compute_manifold(const AABB &a, const AABB &b) noexcept {
    const F32 ox = std::min(a.max.x, b.max.x) - std::max(a.min.x, b.min.x);
    const F32 oy = std::min(a.max.y, b.max.y) - std::max(a.min.y, b.min.y);
    const F32 oz = std::min(a.max.z, b.max.z) - std::max(a.min.z, b.min.z);

    if (ox <= 0.0f || oy <= 0.0f || oz <= 0.0f) {
        return {false, {}};
    }

    // Pick the axis with the smallest penetration.
    Vec3 normal;
    F32 depth;
    if (ox <= oy && ox <= oz) {
        depth = ox;
        normal = {1.0f, 0.0f, 0.0f};
    } else if (oy <= ox && oy <= oz) {
        depth = oy;
        normal = {0.0f, 1.0f, 0.0f};
    } else {
        depth = oz;
        normal = {0.0f, 0.0f, 1.0f};
    }

    // Flip normal so it points from b toward a.
    const Vec3 d = a.center() - b.center();
    if (glm::dot(d, normal) < 0.0f) {
        normal = -normal;
    }

    // Contact point: centre of the overlap region along each axis.
    const Vec3 point = {
        (std::max(a.min.x, b.min.x) + std::min(a.max.x, b.max.x)) * 0.5f,
        (std::max(a.min.y, b.min.y) + std::min(a.max.y, b.max.y)) * 0.5f,
        (std::max(a.min.z, b.min.z) + std::min(a.max.z, b.max.z)) * 0.5f,
    };

    return {true, {Thing::nil(), Thing::nil(), normal, point, depth}};
}

/// @brief Computes the contact manifold between two ColliderParts.
inline CollisionManifoldResult compute_manifold(const ColliderPart &a,
                                                const ColliderPart &b) noexcept {
    return compute_manifold(a.aabb, b.aabb);
}

} // namespace fr

FR_TYPE(fr::MassPart);
FR_TYPE(fr::ColliderPart);
FR_TYPE(fr::CollisionEventsPart);
FR_TYPE(fr::PhysicsMaterialPart);
FR_TYPE(fr::RigidBodyPart);
