/**
 * @file systems.cpp
 * @author Kiju
 *
 * @brief Physics system implementations.
 *
 * @details
 * Systems are registered with the World and run each frame in stage order.
 * The collision pipeline is two-pass:
 *
 * @warning Majority of this code was generated by a Clanker.
 */

#include <cmath>

#include "fr/core/math.hpp"
#include "fr/data/parts.hpp"
#include "fr/data/world.hpp"
#include "fr/physics/parts.hpp"
#include "fr/physics/resources.hpp"
#include "fr/physics/systems.hpp"
#include "glm/geometric.hpp"
#include "glm/gtc/quaternion.hpp"
#include "glm/matrix.hpp"

namespace fr {

// =================================================================== Internals

/**
 * @brief Transforms a local-space AABB and its collider offset into world space.
 *
 * @details
 * Centre is mapped by the full 4x4 TRS matrix (handles translation + rotation + scale).
 * Half-extents are expanded using the absolute column sums of the upper 3x3, which gives
 * a tight world-space AABB without needing to test all 8 corners.
 *
 * @param local Local-space AABB (no offset applied yet).
 * @param offset Local-space collider offset (added to the AABB centre before transforming).
 * @param mat World transform matrix (column-major, glm layout).
 */
static AABB do_aabb_to_world(const AABB &local, const Vec3 &offset, const Mat4 &mat) noexcept {
    const Vec3 local_center = local.center() + offset;
    const Vec3 world_center = Vec3(mat * Vec4(local_center, 1.0f));

    const Vec3 local_half = local.half_extents();
    Vec3 world_half{0.0f};

    for (int i = 0; i < 3; ++i) {
        for (int j = 0; j < 3; ++j) {
            world_half[i] += std::abs(mat[j][i]) * local_half[j];
        }
    }

    return AABB::from_center(world_center, world_half);
}

/**
 * @brief Transforms a local-space `ColliderPart` into world space.
 *
 * @param local Source collider (local space, offset included).
 * @param mat World transform matrix.
 * @return A new `ColliderPart` with world-space AABB; offset is zeroed (already applied).
 */
static ColliderPart do_collider_to_world(const ColliderPart &local, const Mat4 &mat) noexcept {
    return ColliderPart::make(do_aabb_to_world(local.aabb, local.offset, mat));
}

/**
 * @brief Pushes all cells covered by a world-space AABB into the spatial hash grid.
 *
 * @param grid Grid to push into.
 * @param thing Owner of the collider.
 * @param ws_aabb World-space bounding box.
 */
static void do_push_aabb_cells(impl::SpatialHashGrid &grid, Thing thing,
                               const AABB &ws_aabb) noexcept {
    const F32 cell_size = grid.options().cell_size;
    const auto cell = [&](F32 v) { return static_cast<S32>(std::floor(v / cell_size)); };

    const S32 x0 = cell(ws_aabb.min.x), x1 = cell(ws_aabb.max.x);
    const S32 y0 = cell(ws_aabb.min.y), y1 = cell(ws_aabb.max.y);
    const S32 z0 = cell(ws_aabb.min.z), z1 = cell(ws_aabb.max.z);

    for (S32 x = x0; x <= x1; ++x) {
        for (S32 y = y0; y <= y1; ++y) {
            for (S32 z = z0; z <= z1; ++z) {
                grid.push(thing, x, y, z);
            }
        }
    }
}

// ===================================================================== Systems

/// @brief Broadphase collision detection system.
void broadphase_collision_detection_system(Scope scope) {
    PhysicsState &state = scope.get_resource<PhysicsState>();
    state.grid.clear();

    for (auto [thing, wt, collider] : scope.query<WorldTransformPart, ColliderPart>()) {
        const AABB ws = do_aabb_to_world(collider.aabb, collider.offset, wt.matrix);
        do_push_aabb_cells(state.grid, thing, ws);
    }

    state.grid.sort();
}

/// @brief Narrowphase collision detection system.
void narrowphase_collision_detection_system(Scope scope) {
    PhysicsState &state = scope.get_resource<PhysicsState>();

    // Reset per-frame state.
    state.manifold_pool.clear();
    for (auto [thing, events] : scope.query<CollisionEventsPart>()) {
        (void)thing;
        events.count = 0;
    }

    const auto &entries = state.grid.entries();
    const USize n = entries.size();

    USize i = 0;
    while (i < n) {
        USize j = i + 1;
        while (j < n && entries[j].hash == entries[i].hash) {
            ++j;
        }

        for (USize a = i; a < j; ++a) {
            for (USize b = a + 1; b < j; ++b) {
                const Thing ta = entries[a].thing;
                const Thing tb = entries[b].thing;

                if (ta == tb) {
                    continue;
                }

                WorldTransformPart *wt_a = scope.try_get<WorldTransformPart>(ta);
                ColliderPart *col_a = scope.try_get<ColliderPart>(ta);
                WorldTransformPart *wt_b = scope.try_get<WorldTransformPart>(tb);
                ColliderPart *col_b = scope.try_get<ColliderPart>(tb);

                if (!wt_a || !col_a || !wt_b || !col_b) {
                    continue;
                }

                const ColliderPart ws_a = do_collider_to_world(*col_a, wt_a->matrix);
                const ColliderPart ws_b = do_collider_to_world(*col_b, wt_b->matrix);

                if (!check_collision(ws_a, ws_b)) {
                    continue;
                }

                bool already_recorded = false;
                for (const CollisionManifold &m : state.manifold_pool.manifolds()) {
                    if ((m.a == ta && m.b == tb) || (m.a == tb && m.b == ta)) {
                        already_recorded = true;
                        break;
                    }
                }

                if (already_recorded) {
                    continue;
                }

                CollisionManifoldResult mr = compute_manifold(ws_a, ws_b);
                if (!mr.hit) {
                    continue;
                }

                mr.manifold.a = ta;
                mr.manifold.b = tb;
                state.manifold_pool.push(mr.manifold);

                if (CollisionEventsPart *ea = scope.try_get<CollisionEventsPart>(ta)) {
                    ea->insert(tb);
                }
                if (CollisionEventsPart *eb = scope.try_get<CollisionEventsPart>(tb)) {
                    eb->insert(ta);
                }
            }
        }

        i = j;
    }
}

// --------------------------------------------------------------------- Helpers

/// @brief Returns the world-space inverse inertia tensor for a body.
static Mat3 do_world_inertia_inv(const MassPart *mass, const Quat &rot) noexcept {
    if (!mass) {
        return Mat3(0.0f);
    }

    const Mat3 R = glm::mat3_cast(rot);
    return R * mass->inv_inertia * glm::transpose(R);
}

/// @brief Returns the world-space position of a body's center of mass.
static Vec3 do_world_com(const MassPart *mass, const WorldTransformPart &wt) noexcept {
    if (!mass || mass->com == Vec3{0.0f}) {
        return wt.position;
    }

    return wt.position + glm::mat3_cast(wt.rotation) * mass->com;
}

// --------------------------------------------------------------------- Systems

void rigit_body_force_system(Scope scope) {
    const PhysicsState &state = scope.get_resource<PhysicsState>();
    const F32 dt = state.dt;
    const Vec3 gravity = state.options.gravity;

    for (auto [thing, rb, lt] : scope.query<RigidBodyPart, LocalTransformPart>()) {
        if (rb.inv_mass <= 0.0f) {
            continue;
        }

        rb.velocity += (rb.force * rb.inv_mass + gravity) * dt;
        rb.force = {0.0f, 0.0f, 0.0f};
        lt.position += rb.velocity * dt;

        const MassPart *mass = scope.try_get<MassPart>(thing);
        const WorldTransformPart *wt = scope.try_get<WorldTransformPart>(thing);

        if (mass && wt) {
            const Mat3 I_world_inv = do_world_inertia_inv(mass, wt->rotation);
            rb.angular_velocity += I_world_inv * rb.torque * dt;
            rb.torque = {0.0f, 0.0f, 0.0f};

            const Quat omega_quat(0.0f, rb.angular_velocity.x, rb.angular_velocity.y,
                                  rb.angular_velocity.z);

            lt.rotation = glm::normalize(lt.rotation + 0.5f * omega_quat * lt.rotation * dt);
        }
    }
}

/// @brief Resolves collision constraints with full rigid-body impulse response.
void rigit_body_collision_resolution_system(Scope scope) {
    constexpr F32 SLOP = 0.005f;
    constexpr F32 BAUMGARTE = 0.2f;

    PhysicsState &state = scope.get_resource<PhysicsState>();

    for (const CollisionManifold &m : state.manifold_pool.manifolds()) {
        RigidBodyPart *rb_a = scope.try_get<RigidBodyPart>(m.a);
        RigidBodyPart *rb_b = scope.try_get<RigidBodyPart>(m.b);

        const F32 inv_a = rb_a ? rb_a->inv_mass : 0.0f;
        const F32 inv_b = rb_b ? rb_b->inv_mass : 0.0f;

        if (inv_a + inv_b <= 0.0f) {
            continue; // both static
        }

        // Fetch rotational data.
        const MassPart *mass_a = scope.try_get<MassPart>(m.a);
        const MassPart *mass_b = scope.try_get<MassPart>(m.b);
        const WorldTransformPart *wt_a = scope.try_get<WorldTransformPart>(m.a);
        const WorldTransformPart *wt_b = scope.try_get<WorldTransformPart>(m.b);

        const Mat3 I_inv_a = wt_a ? do_world_inertia_inv(mass_a, wt_a->rotation) : Mat3(0.0f);
        const Mat3 I_inv_b = wt_b ? do_world_inertia_inv(mass_b, wt_b->rotation) : Mat3(0.0f);

        // Moment arms: from each body's COM to the contact point.
        const Vec3 com_a = wt_a ? do_world_com(mass_a, *wt_a) : Vec3{0.0f};
        const Vec3 com_b = wt_b ? do_world_com(mass_b, *wt_b) : Vec3{0.0f};
        const Vec3 r_a = m.point - com_a;
        const Vec3 r_b = m.point - com_b;

        // Relative velocity at the contact point (linear + rotational).
        const Vec3 ang_a = rb_a ? rb_a->angular_velocity : Vec3{0.0f};
        const Vec3 ang_b = rb_b ? rb_b->angular_velocity : Vec3{0.0f};
        const Vec3 v_a = (rb_a ? rb_a->velocity : Vec3{0.0f}) + glm::cross(ang_a, r_a);
        const Vec3 v_b = (rb_b ? rb_b->velocity : Vec3{0.0f}) + glm::cross(ang_b, r_b);
        const Vec3 rel_vel = v_a - v_b;
        const F32 vn = glm::dot(rel_vel, m.normal);

        if (vn < 0.0f) {
            // Normal impuls

            // Rotational contribution to effective mass along the normal.
            const Vec3 rn_a = glm::cross(r_a, m.normal);
            const Vec3 rn_b = glm::cross(r_b, m.normal);
            const F32 K =
                inv_a + inv_b + glm::dot(rn_a, I_inv_a * rn_a) + glm::dot(rn_b, I_inv_b * rn_b);

            const F32 e = (rb_a && rb_b) ? std::sqrt(rb_a->restitution * rb_b->restitution)
                                         : (rb_a ? rb_a->restitution : rb_b->restitution);

            const F32 j = -(1.0f + e) * vn / K;
            const Vec3 impulse = m.normal * j;

            if (rb_a && inv_a > 0.0f) {
                rb_a->velocity += impulse * inv_a;
                rb_a->angular_velocity += I_inv_a * glm::cross(r_a, impulse);
            }

            if (rb_b && inv_b > 0.0f) {
                rb_b->velocity -= impulse * inv_b;
                rb_b->angular_velocity -= I_inv_b * glm::cross(r_b, impulse);
            }

            // Friction impulse

            const Vec3 vel_t = rel_vel - vn * m.normal;
            const F32 vt_len = glm::length(vel_t);

            if (vt_len > 1e-6f) {
                const Vec3 tangent = vel_t / vt_len;

                // Rotational contribution to effective mass along the tangent.
                const Vec3 rt_a = glm::cross(r_a, tangent);
                const Vec3 rt_b = glm::cross(r_b, tangent);
                const F32 K_t =
                    inv_a + inv_b + glm::dot(rt_a, I_inv_a * rt_a) + glm::dot(rt_b, I_inv_b * rt_b);

                const F32 mu = (rb_a && rb_b) ? std::sqrt(rb_a->friction * rb_b->friction)
                                              : (rb_a ? rb_a->friction : rb_b->friction);

                const F32 jt = math::max(-vt_len / K_t, -mu * j);
                const Vec3 f_impulse = tangent * jt;

                if (rb_a && inv_a > 0.0f) {
                    rb_a->velocity += f_impulse * inv_a;
                    rb_a->angular_velocity += I_inv_a * glm::cross(r_a, f_impulse);
                }

                if (rb_b && inv_b > 0.0f) {
                    rb_b->velocity -= f_impulse * inv_b;
                    rb_b->angular_velocity -= I_inv_b * glm::cross(r_b, f_impulse);
                }
            }
        }

        // Baumgarte correction to prevent penetration.
        const F32 corr_mag = math::max(m.depth - SLOP, 0.0f) * BAUMGARTE / (inv_a + inv_b);
        const Vec3 correction = m.normal * corr_mag;

        if (rb_a && inv_a > 0.0f) {
            if (LocalTransformPart *lt = scope.try_get<LocalTransformPart>(m.a)) {
                lt->position += correction * inv_a;
            }
        }
        if (rb_b && inv_b > 0.0f) {
            if (LocalTransformPart *lt = scope.try_get<LocalTransformPart>(m.b)) {
                lt->position -= correction * inv_b;
            }
        }
    }
}

} // namespace fr
